updates

diff --git a/dot_bash_functions_wsl2 b/dot_bash_functions_wsl2
--- a/dot_bash_functions_wsl2
+++ b/dot_bash_functions_wsl2
@@ -27,6 +27,38 @@ command_not_found_handle() {
 function idea() {
   local dist="$HOME/.cache/JetBrains/RemoteDev/dist"
   local ij
+  ij=$(jetbrains) || return $?
+
+  local exe_path="$dist/$ij/bin/idea.sh"
+  # local exe_path="$dist/$ij/bin/remote-dev-server.sh"
+  if [[ ! -x "$exe_path" ]]; then
+    echo "Executable not found: $exe_path" >&2
+    return 2
+  fi
+
+  "$exe_path" "$@"
+}
+
+function remote-dev-server() {
+  local dist="$HOME/.cache/JetBrains/RemoteDev/dist"
+  local ij
+  ij=$(jetbrains) || return $?
+
+  # local exe_path="$dist/$ij/bin/idea.sh"
+  local exe_path="$dist/$ij/bin/remote-dev-server.sh"
+  if [[ ! -x "$exe_path" ]]; then
+    echo "Executable not found: $exe_path" >&2
+    return 2
+  fi
+
+  "$exe_path" "$@"
+}
+
+
+jetbrains() {
+  local dist="$HOME/.cache/JetBrains/RemoteDev/dist"
+  local jetbrains
+
   # find:
   #  -maxdepth 1 to not recurse into subdirs
   #  -name to only find dirs that match the pattern
@@ -36,19 +68,23 @@ function idea() {
   #  -t splits to 2 groups.
   #  -k says 2nd group starting with the 1st character.
   #  -V is symantic version sort
-  ij=$(find "$dist" -maxdepth 1 -name "*_ideaIU-*" -type d -printf '%P\n' | sort -V -t'-' -k 2.1 | tail -1)
+  jetbrains=$(find "$dist" -maxdepth 1 -name "*_idea*-*" -type d -printf '%P\n' | sort -V -t'-' -k 2.1 | tail -1)
 
-  if [[ -z "$ij" ]]; then
+  if [[ -z "$jetbrains" ]]; then
     echo "No IntelliJ IDEA version found in $dist" >&2
     return 1
   fi
-
-  local exe_path="$dist/$ij/bin/idea.sh"
-  if [[ ! -x "$exe_path" ]]; then
-    echo "Executable not found: $exe_path" >&2
-    return 2
-  fi
-
-  "$exe_path" "$@"
+  echo "$jetbrains"
 }
 
+j8() {
+  JAVA_HOME=$JAVA_8_HOME "$@"
+}
+
+j17() {
+  JAVA_HOME=$JAVA_17_HOME "$@"
+} 
+
+j21() {
+  JAVA_HOME=$JAVA_21_HOME "$@"
+} 
